---

- name: install
  include_tasks: install.yml
  when: lxd_setup == "full" or lxd_setup == "install"

- name: configure
  import_tasks: configure.yml
  when: lxd_setup == "full" or lxd_setup == "configure"
